import { jsPDF } from 'jspdf'
import autoTable, { type CellHookData } from 'jspdf-autotable'

// --- Types ---

export interface AlertItem {
  id: string | number
  sev: 'critical' | 'high' | 'medium' | 'low'
  cat: string
  msg: string
  time: string
}

export interface TrustPoint {
  t: string
  score: number
}

export interface TranscriptLine {
  speaker?: string
  timestamp: string
  text: string
  suspicious?: boolean
}

export interface ReportPayload {
  id: string
  title: string
  date: string
  duration: string
  durationMins: number
  meetingType?: string
  participants: number
  trustAvg: number
  visualScore?: number
  audioScore?: number
  dominantEmotions?: string[]
  modelUsed?: string
  alerts: {
    total: number
    critical: number
    high: number
    medium: number
    low: number
  }
  timeline: AlertItem[]
  trustCurve: TrustPoint[]
  transcript?: TranscriptLine[]
}

// --- Color Palette (white/light theme) ---

const C = {
  // White backgrounds
  pageBg: [255, 255, 255] as [number, number, number],
  headerBg: [248, 250, 252] as [number, number, number],   // very light gray
  rowAlt: [248, 250, 252] as [number, number, number],     // alternating table row

  // Text (dark on white)
  textPrimary: [15, 23, 42] as [number, number, number],   // near-black
  textSecondary: [51, 65, 85] as [number, number, number], // slate-700
  textMuted: [100, 116, 139] as [number, number, number],  // slate-500

  // Brand accent
  cyan: [14, 165, 233] as [number, number, number],        // sky-500 — readable on white
  cyanLight: [224, 242, 254] as [number, number, number],  // sky-100

  // Borders
  border: [226, 232, 240] as [number, number, number],     // slate-200
  borderMid: [203, 213, 225] as [number, number, number],  // slate-300

  // Risk colors
  green: [22, 163, 74] as [number, number, number],        // green-600
  greenLight: [220, 252, 231] as [number, number, number],
  amber: [217, 119, 6] as [number, number, number],        // amber-600
  amberLight: [254, 243, 199] as [number, number, number],
  orange: [234, 88, 12] as [number, number, number],       // orange-600
  orangeLight: [255, 237, 213] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],          // red-600
  redLight: [254, 226, 226] as [number, number, number],
} as const

// A4 dimensions (mm)
const PAGE_W = 210
const PAGE_H = 297
const MARGIN = 20
const CONTENT_W = PAGE_W - MARGIN * 2
const FOOTER_Y = PAGE_H - 12

// --- Utility helpers ---

function setFill(doc: jsPDF, color: readonly [number, number, number]) {
  doc.setFillColor(color[0], color[1], color[2])
}

function setDraw(doc: jsPDF, color: readonly [number, number, number]) {
  doc.setDrawColor(color[0], color[1], color[2])
}

function setTxt(doc: jsPDF, color: readonly [number, number, number]) {
  doc.setTextColor(color[0], color[1], color[2])
}

function riskColor(score: number): readonly [number, number, number] {
  if (score >= 90) return C.green
  if (score >= 75) return C.cyan
  if (score >= 60) return C.amber
  return C.red
}

function riskColorLight(score: number): readonly [number, number, number] {
  if (score >= 90) return C.greenLight
  if (score >= 75) return C.cyanLight
  if (score >= 60) return C.amberLight
  return C.redLight
}

function riskLabel(score: number): string {
  if (score >= 90) return 'LOW RISK'
  if (score >= 75) return 'MODERATE'
  if (score >= 60) return 'HIGH RISK'
  return 'CRITICAL'
}

function sevColor(sev: string): readonly [number, number, number] {
  switch (sev) {
    case 'critical': return C.red
    case 'high': return C.orange
    case 'medium': return C.amber
    default: return C.cyan
  }
}

function sevColorLight(sev: string): readonly [number, number, number] {
  switch (sev) {
    case 'critical': return C.redLight
    case 'high': return C.orangeLight
    case 'medium': return C.amberLight
    default: return C.cyanLight
  }
}

/** Horizontal divider line */
function hRule(doc: jsPDF, y: number, color: readonly [number, number, number] = C.border) {
  setDraw(doc, color)
  doc.setLineWidth(0.25)
  doc.line(MARGIN, y, PAGE_W - MARGIN, y)
}

/** Draw page footer */
function drawFooter(doc: jsPDF, pageNum: number, totalPages: number, generatedAt: string) {
  hRule(doc, FOOTER_Y - 4, C.borderMid)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  setTxt(doc, C.textMuted)
  doc.text('Generated by RealSync  |  Confidential', MARGIN, FOOTER_Y)
  doc.text(generatedAt, PAGE_W / 2, FOOTER_Y, { align: 'center' })
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, FOOTER_Y, { align: 'right' })
}

/** Draw page background (white) */
function drawPageBackground(doc: jsPDF) {
  setFill(doc, C.pageBg)
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F')
}

/** Load logo as base64 */
async function loadLogoBase64(): Promise<string | null> {
  try {
    const resp = await fetch('/realsync-logo.png')
    if (!resp.ok) return null
    const blob = await resp.blob()
    return new Promise((resolve) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(reader.result as string)
      reader.onerror = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

/** Small colored circle dot for severity */
function sevDot(doc: jsPDF, x: number, y: number, sev: string) {
  const color = sevColor(sev)
  setFill(doc, color)
  doc.circle(x, y, 1.5, 'F')
}

/** Draw a metric card: label + large number */
function metricCard(
  doc: jsPDF,
  x: number, y: number, w: number, h: number,
  label: string,
  value: string,
  valueColor: readonly [number, number, number],
) {
  // Card border
  setDraw(doc, C.border)
  setFill(doc, C.pageBg)
  doc.setLineWidth(0.3)
  doc.rect(x, y, w, h, 'FD')

  // Label
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  setTxt(doc, C.textMuted)
  doc.text(label.toUpperCase(), x + 4, y + 6)

  // Value
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  setTxt(doc, valueColor)
  doc.text(value, x + 4, y + 17)
}

/** Draw a progress bar */
function progressBar(
  doc: jsPDF,
  x: number, y: number, w: number,
  score: number,
  color: readonly [number, number, number],
) {
  const h = 3
  // Track
  setFill(doc, C.border)
  doc.roundedRect(x, y, w, h, 1.5, 1.5, 'F')
  // Fill
  const fillW = Math.max(3, (score / 100) * w)
  setFill(doc, color)
  doc.roundedRect(x, y, fillW, h, 1.5, 1.5, 'F')
}

/** Section heading with cyan left accent bar */
function sectionHeading(doc: jsPDF, y: number, title: string): number {
  setFill(doc, C.cyan)
  doc.rect(MARGIN, y, 3, 6, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  setTxt(doc, C.textPrimary)
  doc.text(title, MARGIN + 6, y + 4.5)

  return y + 10
}

// --- Page 1: Cover ---

function buildPage1(
  doc: jsPDF,
  report: ReportPayload,
  logoBase64: string | null,
  generatedAt: string,
) {
  drawPageBackground(doc)

  // ── Top header band ──────────────────────────────────────────
  setFill(doc, C.headerBg)
  doc.rect(0, 0, PAGE_W, 50, 'F')

  // Cyan top accent line
  setFill(doc, C.cyan)
  doc.rect(0, 0, PAGE_W, 1.5, 'F')

  // Logo (top-left)
  if (logoBase64) {
    try {
      doc.addImage(logoBase64, 'PNG', MARGIN, 10, 22, 22)
    } catch {
      // Logo failed — draw text fallback
    }
  }

  // RealSync wordmark
  const wordmarkX = logoBase64 ? MARGIN + 26 : MARGIN
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  setTxt(doc, C.textPrimary)
  doc.text('RealSync', wordmarkX, 22)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  setTxt(doc, C.textMuted)
  doc.text('AI-Powered Meeting Authenticity Platform', wordmarkX, 29)

  // "SECURITY AUDIT REPORT" label (right side)
  setFill(doc, C.cyanLight)
  doc.rect(PAGE_W - MARGIN - 54, 15, 54, 12, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  setTxt(doc, C.cyan)
  doc.text('SECURITY AUDIT REPORT', PAGE_W - MARGIN - 27, 22.5, { align: 'center' })

  let y = 62

  // ── Report title ────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  setTxt(doc, C.textPrimary)
  doc.text('Meeting Authenticity Report', MARGIN, y)
  y += 7

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  setTxt(doc, C.cyan)
  doc.text(report.title, MARGIN, y)
  y += 8

  hRule(doc, y)
  y += 8

  // ── Session detail row ──────────────────────────────────────
  const detailItems = [
    { label: 'Date', value: report.date },
    { label: 'Duration', value: report.duration },
    { label: 'Meeting Type', value: (report.meetingType ?? 'Standard').charAt(0).toUpperCase() + (report.meetingType ?? 'Standard').slice(1) },
    { label: 'Session ID', value: report.id.slice(0, 8).toUpperCase() },
  ]

  const colW = CONTENT_W / detailItems.length
  detailItems.forEach((item, i) => {
    const cx = MARGIN + i * colW
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    setTxt(doc, C.textMuted)
    doc.text(item.label.toUpperCase(), cx, y)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    setTxt(doc, C.textPrimary)
    doc.text(item.value, cx, y + 6)
  })

  y += 18
  hRule(doc, y)
  y += 12

  // ── Trust score (large centrepiece) ─────────────────────────
  const scoreColor = riskColor(report.trustAvg)
  const scoreBgColor = riskColorLight(report.trustAvg)
  const rLabel = riskLabel(report.trustAvg)

  // Score box
  setFill(doc, scoreBgColor)
  setDraw(doc, scoreColor)
  doc.setLineWidth(0.5)
  doc.roundedRect(MARGIN, y, 60, 38, 3, 3, 'FD')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(36)
  setTxt(doc, scoreColor)
  doc.text(`${report.trustAvg}%`, MARGIN + 30, y + 20, { align: 'center' })

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  setTxt(doc, scoreColor)
  doc.text('TRUST SCORE', MARGIN + 30, y + 28, { align: 'center' })

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  setTxt(doc, scoreColor)
  doc.text(rLabel, MARGIN + 30, y + 34.5, { align: 'center' })

  // Severity breakdown cards (right side)
  const cards = [
    { label: 'Critical', value: report.alerts.critical, color: C.red },
    { label: 'High', value: report.alerts.high, color: C.orange },
    { label: 'Medium', value: report.alerts.medium, color: C.amber },
    { label: 'Low', value: report.alerts.low, color: C.cyan },
  ]

  const cardW = (CONTENT_W - 66) / 4
  cards.forEach((card, i) => {
    const cx = MARGIN + 66 + i * (cardW + 2)
    metricCard(doc, cx, y, cardW, 38, card.label, String(card.value), card.value > 0 ? card.color : C.textMuted)
  })

  y += 50

  // ── Executive summary block ─────────────────────────────────
  setFill(doc, C.headerBg)
  setDraw(doc, C.border)
  doc.setLineWidth(0.3)
  doc.roundedRect(MARGIN, y, CONTENT_W, 30, 2, 2, 'FD')

  // Cyan left accent
  setFill(doc, C.cyan)
  doc.roundedRect(MARGIN, y, 3, 30, 1.5, 1.5, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  setTxt(doc, C.cyan)
  doc.text('EXECUTIVE SUMMARY', MARGIN + 7, y + 7)

  const summaryText = buildSummaryText(report)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  setTxt(doc, C.textSecondary)
  const summaryLines = doc.splitTextToSize(summaryText, CONTENT_W - 12)
  doc.text(summaryLines.slice(0, 3), MARGIN + 7, y + 14)

  y += 38

  // ── Alert total count summary ───────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  setTxt(doc, C.textSecondary)
  doc.text(`Total Alerts: ${report.alerts.total}`, MARGIN, y)

  // Progress bar representing severity distribution
  if (report.alerts.total > 0) {
    const barY = y + 4
    const barH = 4
    let barX = MARGIN
    const totalW = CONTENT_W
    const segments = [
      { count: report.alerts.critical, color: C.red },
      { count: report.alerts.high, color: C.orange },
      { count: report.alerts.medium, color: C.amber },
      { count: report.alerts.low, color: C.cyan },
    ]
    setFill(doc, C.border)
    doc.roundedRect(MARGIN, barY, totalW, barH, 2, 2, 'F')
    segments.forEach((seg) => {
      if (seg.count === 0) return
      const segW = (seg.count / report.alerts.total) * totalW
      setFill(doc, seg.color)
      doc.rect(barX, barY, segW, barH, 'F')
      barX += segW
    })
    // Round the right end cap
    setFill(doc, C.pageBg)
    doc.rect(PAGE_W - MARGIN - 2, barY, 2, barH, 'F')
  }

  drawFooter(doc, 1, report.transcript && report.transcript.length > 0 ? 4 : 3, generatedAt)
}

function buildSummaryText(report: ReportPayload): string {
  const rLabel = riskLabel(report.trustAvg).toLowerCase()
  const alertPart = report.alerts.total === 0
    ? 'No alerts were raised during this session — all participants verified as authentic.'
    : `${report.alerts.total} alert${report.alerts.total !== 1 ? 's' : ''} detected (${report.alerts.critical} critical, ${report.alerts.high} high, ${report.alerts.medium} medium, ${report.alerts.low} low).`
  return `Session "${report.title}" completed on ${report.date} with an overall trust score of ${report.trustAvg}%, classified as ${rLabel} risk. ${alertPart} Duration: ${report.duration}.`
}

// --- Page 2: Analysis Summary ---

function buildPage2(
  doc: jsPDF,
  report: ReportPayload,
  generatedAt: string,
  totalPages: number,
) {
  doc.addPage()
  drawPageBackground(doc)

  let y = MARGIN + 2

  // Page title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  setTxt(doc, C.textPrimary)
  doc.text('Analysis Summary', MARGIN, y + 5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  setTxt(doc, C.textMuted)
  doc.text('Detailed breakdown of all AI detection layers applied to this session', MARGIN, y + 12)

  hRule(doc, y + 16)
  y += 24

  // ── Visual Detection ─────────────────────────────────────────
  y = sectionHeading(doc, y, 'Visual Manipulation Detection')

  const visualScore = report.visualScore ?? report.trustAvg
  const vColor = riskColor(visualScore)

  setFill(doc, C.headerBg)
  setDraw(doc, C.border)
  doc.setLineWidth(0.3)
  doc.roundedRect(MARGIN, y, CONTENT_W, 38, 2, 2, 'FD')

  // Score value
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  setTxt(doc, vColor)
  doc.text(`${visualScore}%`, MARGIN + 5, y + 16)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  setTxt(doc, C.textMuted)
  doc.text('Visual Authenticity Score', MARGIN + 5, y + 22)

  progressBar(doc, MARGIN + 5, y + 26, 55, visualScore, vColor)

  // Risk badge
  setFill(doc, riskColorLight(visualScore))
  doc.roundedRect(MARGIN + 5, y + 31, 28, 5, 1.5, 1.5, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  setTxt(doc, vColor)
  doc.text(riskLabel(visualScore), MARGIN + 5 + 14, y + 34.5, { align: 'center' })

  // Model info (right side)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  setTxt(doc, C.textSecondary)
  doc.text('Model:', MARGIN + 70, y + 10)
  doc.setFont('helvetica', 'bold')
  doc.text(report.modelUsed ?? 'Ensemble (CLIP-ViT + Freq + Boundary)', MARGIN + 84, y + 10)

  doc.setFont('helvetica', 'normal')
  setTxt(doc, C.textMuted)
  doc.text('Benchmark: 98.65% accuracy on FaceForensics++ / DFDC', MARGIN + 70, y + 17)

  y += 46

  // ── Audio Analysis ────────────────────────────────────────────
  y = sectionHeading(doc, y, 'Audio Analysis')

  const audioScore = report.audioScore ?? Math.min(100, report.trustAvg + 2)
  const aColor = riskColor(audioScore)

  setFill(doc, C.headerBg)
  setDraw(doc, C.border)
  doc.setLineWidth(0.3)
  doc.roundedRect(MARGIN, y, CONTENT_W, 30, 2, 2, 'FD')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  setTxt(doc, aColor)
  doc.text(`${audioScore}%`, MARGIN + 5, y + 16)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  setTxt(doc, C.textMuted)
  doc.text('Audio Authenticity Score', MARGIN + 5, y + 22)

  progressBar(doc, MARGIN + 5, y + 25, 55, audioScore, aColor)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  setTxt(doc, C.textMuted)
  doc.text('Analyzes voice patterns, codec artifacts, and synthetic speech signatures', MARGIN + 70, y + 14)

  setFill(doc, riskColorLight(audioScore))
  doc.roundedRect(MARGIN + 70, y + 18, 28, 5, 1.5, 1.5, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  setTxt(doc, aColor)
  doc.text(riskLabel(audioScore), MARGIN + 70 + 14, y + 21.5, { align: 'center' })

  y += 38

  // ── Emotion Analysis ──────────────────────────────────────────
  y = sectionHeading(doc, y, 'Emotion Analysis')

  const emotions = report.dominantEmotions?.length
    ? report.dominantEmotions
    : ['Neutral', 'Attentive', 'Engaged']

  setFill(doc, C.headerBg)
  setDraw(doc, C.border)
  doc.setLineWidth(0.3)
  doc.roundedRect(MARGIN, y, CONTENT_W, 24, 2, 2, 'FD')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  setTxt(doc, C.textSecondary)
  doc.text('Dominant Emotions Detected:', MARGIN + 5, y + 8)

  const emotionPillColors: readonly [number, number, number][] = [C.cyan, C.green, C.amber, C.orange, C.red]
  const emotionBgColors: readonly [number, number, number][] = [C.cyanLight, C.greenLight, C.amberLight, C.orangeLight, C.redLight]

  emotions.slice(0, 5).forEach((em, i) => {
    const ex = MARGIN + 5 + i * 36
    setFill(doc, emotionBgColors[i % emotionBgColors.length])
    doc.roundedRect(ex, y + 12, 32, 6, 1.5, 1.5, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    setTxt(doc, emotionPillColors[i % emotionPillColors.length])
    doc.text(em.toUpperCase(), ex + 16, y + 16.5, { align: 'center' })
  })

  y += 32

  // ── Behavioral Analysis ───────────────────────────────────────
  y = sectionHeading(doc, y, 'Behavioral Analysis')

  const behaviorMetrics = [
    { label: 'Gaze Consistency', value: Math.min(100, report.trustAvg + 1) },
    { label: 'Head Pose Stability', value: Math.min(100, report.trustAvg - 1) },
    { label: 'Temporal Coherence', value: report.trustAvg },
  ]

  setFill(doc, C.headerBg)
  setDraw(doc, C.border)
  doc.setLineWidth(0.3)
  doc.roundedRect(MARGIN, y, CONTENT_W, 32, 2, 2, 'FD')

  const bmW = (CONTENT_W - 8) / behaviorMetrics.length
  behaviorMetrics.forEach((bm, i) => {
    const bx = MARGIN + 4 + i * (bmW + 1)
    const col = riskColor(bm.value)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    setTxt(doc, C.textMuted)
    doc.text(bm.label, bx, y + 8)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(16)
    setTxt(doc, col)
    doc.text(`${bm.value}%`, bx, y + 20)

    progressBar(doc, bx, y + 23, bmW - 4, bm.value, col)
  })

  drawFooter(doc, 2, totalPages, generatedAt)
}

// --- Page 3: Alert Timeline ---

function buildPage3(
  doc: jsPDF,
  report: ReportPayload,
  generatedAt: string,
  totalPages: number,
) {
  doc.addPage()
  drawPageBackground(doc)

  let y = MARGIN + 2

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  setTxt(doc, C.textPrimary)
  doc.text('Alert Timeline', MARGIN, y + 5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  setTxt(doc, C.textMuted)
  doc.text('Chronological record of all detection events during this session', MARGIN, y + 12)

  hRule(doc, y + 16)
  y += 24

  // Summary pills row
  const sevCounts = [
    { label: 'Critical', count: report.alerts.critical, color: C.red, bgColor: C.redLight },
    { label: 'High', count: report.alerts.high, color: C.orange, bgColor: C.orangeLight },
    { label: 'Medium', count: report.alerts.medium, color: C.amber, bgColor: C.amberLight },
    { label: 'Low', count: report.alerts.low, color: C.cyan, bgColor: C.cyanLight },
  ]

  const pillW = (CONTENT_W - 9) / 4
  sevCounts.forEach((s, i) => {
    const px = MARGIN + i * (pillW + 3)
    setFill(doc, s.bgColor)
    setDraw(doc, s.color)
    doc.setLineWidth(0.3)
    doc.roundedRect(px, y, pillW, 16, 2, 2, 'FD')

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    setTxt(doc, s.color)
    doc.text(s.label.toUpperCase(), px + 5, y + 6.5)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text(String(s.count), px + 5, y + 14)
  })

  y += 22

  if (report.timeline.length === 0) {
    setFill(doc, C.greenLight)
    setDraw(doc, C.green)
    doc.setLineWidth(0.3)
    doc.roundedRect(MARGIN, y, CONTENT_W, 16, 2, 2, 'FD')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    setTxt(doc, C.green)
    doc.text('No alerts detected — session verified as clean', PAGE_W / 2, y + 10, { align: 'center' })
    drawFooter(doc, 3, totalPages, generatedAt)
    return
  }

  // Alert table using autoTable
  const tableBody = report.timeline.map((alert) => [
    alert.time,
    alert.sev.toUpperCase(),
    alert.cat,
    alert.msg.length > 80 ? alert.msg.slice(0, 80) + '...' : alert.msg,
  ])

  autoTable(doc, {
    startY: y,
    head: [['Time', 'Severity', 'Category', 'Description']],
    body: tableBody,
    theme: 'grid',
    headStyles: {
      fillColor: [248, 250, 252],
      textColor: [15, 23, 42],
      fontStyle: 'bold',
      fontSize: 8,
      lineColor: [203, 213, 225],
      lineWidth: 0.3,
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
      textColor: [51, 65, 85],
      lineColor: [226, 232, 240],
      lineWidth: 0.2,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 22, fontStyle: 'bold' },
      2: { cellWidth: 38 },
      3: { cellWidth: 'auto' },
    },
    margin: { left: MARGIN, right: MARGIN },
    didParseCell: (data: CellHookData) => {
      if (data.section === 'body' && data.column.index === 1) {
        const raw = data.row.raw
        const sev = (Array.isArray(raw) ? String(raw[1] ?? '') : '').toLowerCase()
        const color = sevColor(sev)
        data.cell.styles.textColor = [color[0], color[1], color[2]]
      }
    },
  })

  drawFooter(doc, 3, totalPages, generatedAt)
}

// --- Page 4: Transcript ---

function buildPage4(
  doc: jsPDF,
  report: ReportPayload,
  generatedAt: string,
  totalPages: number,
) {
  doc.addPage()
  drawPageBackground(doc)

  let y = MARGIN + 2

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  setTxt(doc, C.textPrimary)
  doc.text('Session Transcript', MARGIN, y + 5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  setTxt(doc, C.textMuted)
  doc.text('Timestamped transcript of meeting communications', MARGIN, y + 12)

  hRule(doc, y + 16)
  y += 24

  if (!report.transcript || report.transcript.length === 0) {
    setFill(doc, C.headerBg)
    setDraw(doc, C.border)
    doc.setLineWidth(0.3)
    doc.roundedRect(MARGIN, y, CONTENT_W, 16, 2, 2, 'FD')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    setTxt(doc, C.textMuted)
    doc.text('No transcript available for this session', PAGE_W / 2, y + 10, { align: 'center' })
    drawFooter(doc, 4, totalPages, generatedAt)
    return
  }

  // Transcript table
  const transcriptBody = report.transcript.slice(0, 60).map((line) => [
    line.timestamp,
    line.speaker || '--',
    line.text.length > 100 ? line.text.slice(0, 100) + '...' : line.text,
  ])

  autoTable(doc, {
    startY: y,
    head: [['Timestamp', 'Speaker', 'Text']],
    body: transcriptBody,
    theme: 'striped',
    headStyles: {
      fillColor: [248, 250, 252],
      textColor: [15, 23, 42],
      fontStyle: 'bold',
      fontSize: 8,
      lineColor: [203, 213, 225],
      lineWidth: 0.3,
    },
    styles: {
      fontSize: 7.5,
      cellPadding: 2.5,
      textColor: [51, 65, 85],
      lineColor: [226, 232, 240],
      lineWidth: 0.2,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 28 },
      2: { cellWidth: 'auto' },
    },
    margin: { left: MARGIN, right: MARGIN },
    didParseCell: (data: CellHookData) => {
      if (data.section === 'body' && data.column.index === 1) {
        const raw = data.row.raw
        const speaker = Array.isArray(raw) ? String(raw[1] ?? '') : ''
        if (speaker && speaker !== '--') {
          data.cell.styles.textColor = [14, 165, 233] // cyan
          data.cell.styles.fontStyle = 'bold'
        }
      }
    },
  })

  if (report.transcript.length > 60) {
    const finalY = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 10
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    setTxt(doc, C.textMuted)
    doc.text(`Showing 60 of ${report.transcript.length} transcript lines`, MARGIN, finalY + 6)
  }

  drawFooter(doc, 4, totalPages, generatedAt)
}

// --- Main entry point ---

export async function generateReport(report: ReportPayload): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const generatedAt = new Date().toLocaleString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })

  const hasTranscript = report.transcript && report.transcript.length > 0
  const totalPages = hasTranscript ? 4 : 3

  // Load logo async before building pages
  const logoBase64 = await loadLogoBase64()

  buildPage1(doc, report, logoBase64, generatedAt)
  buildPage2(doc, report, generatedAt, totalPages)
  buildPage3(doc, report, generatedAt, totalPages)

  if (hasTranscript) {
    buildPage4(doc, report, generatedAt, totalPages)
  }

  const safeTitle = report.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()
  doc.save(`realsync-report-${safeTitle}-${report.id}.pdf`)
}
